export const ADMIN_HOME_FETCH_SUCCESS = 'ADMIN_HOME_FETCH_SUCCESS';
export const ADMIN_HOME_ADD_SUCCESS = 'ADMIN_HOME_ADD_SUCCESS';


export const ADMIN_EXAMPLE_LIST_DATA_TABLE_VUE_BOOTSTRAPETCH_SUCCESS = 'ADMIN_EXAMPLE_LIST_DATA_TABLE_VUE_BOOTSTRAPETCH_SUCCESS'; 